version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build: ./backend
    container_name: backend_clean
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:eventdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/events/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Frontend Nginx (Versão Limpa)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_clean
    container_name: frontend_clean
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/events"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  backend_data:

networks:
  default:
    driver: bridge
